name: 'medallion_lab'
version: '1.0.0'

profile: 'medallion_lab'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  medallion_lab:
    raw_customers:
      +column_types:
        customer_id: integer
        customer_name: varchar
        email: varchar
        city: varchar
        state: varchar
        created_at: varchar
    raw_products:
      +column_types:
        product_id: integer
        product_name: varchar
        category: varchar
        price: double
    raw_orders:
      +column_types:
        order_id: integer
        customer_id: integer
        order_status: varchar
        total_amount: double
        order_date: varchar
    raw_order_items:
      +column_types:
        item_id: integer
        order_id: integer
        product_id: integer
        quantity: integer
        unit_price: double

models:
  medallion_lab:
    bronze:
      +materialized: view
      +tags: ['bronze']
    silver:
      +materialized: table
      +tags: ['silver']
    gold:
      +materialized: table
      +tags: ['gold']